"""Adiciona PlayerProgress e atualiza modelos

Revision ID: 0277a773363b
Revises: 469616f5579a
Create Date: 2025-05-18 01:16:24.930717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0277a773363b'
down_revision = '469616f5579a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hordes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('math_subject', sa.String(length=100), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('monster_count', sa.Integer(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('is_boss_horde', sa.Boolean(), nullable=True),
    sa.Column('required_hordes_completed', sa.Integer(), nullable=True),
    sa.Column('difficulty_multiplier', sa.Float(), nullable=True),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.Column('hordes_completed', sa.Integer(), nullable=True),
    sa.Column('monsters_defeated', sa.Integer(), nullable=True),
    sa.Column('highest_horde_reached', sa.Integer(), nullable=True),
    sa.Column('highest_level_reached', sa.Integer(), nullable=True),
    sa.Column('play_time', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horde_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('horde_id', sa.Integer(), nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=False),
    sa.Column('monsters_defeated', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('completion_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ),
    sa.ForeignKeyConstraint(['horde_id'], ['hordes.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upgrade_level', sa.Integer(), nullable=True))
        batch_op.drop_column('current_level')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_games_played', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('best_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_hordes_completed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('highest_horde_reached', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_monsters_defeated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_play_time', sa.Integer(), nullable=True))

    with op.batch_alter_table('spellbooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_power', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('upgrade_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spellbooks', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('upgrade_level')
        batch_op.drop_column('current_power')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('total_play_time')
        batch_op.drop_column('total_monsters_defeated')
        batch_op.drop_column('highest_horde_reached')
        batch_op.drop_column('total_hordes_completed')
        batch_op.drop_column('best_score')
        batch_op.drop_column('total_games_played')

    with op.batch_alter_table('player_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_level', sa.INTEGER(), nullable=True))
        batch_op.drop_column('upgrade_level')

    op.drop_table('horde_progress')
    op.drop_table('game_sessions')
    op.drop_table('hordes')
    # ### end Alembic commands ###
