"""Adiciona tabela de progresso do jogador

Revision ID: 469616f5579a
Revises: 5436ea6d1c06
Create Date: 2025-05-18 00:51:41.084273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469616f5579a'
down_revision = '5436ea6d1c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('current_xp', sa.Integer(), nullable=True),
    sa.Column('xp_to_next_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_progress')
    # ### end Alembic commands ###
